import Head from 'next/head'
import Layout1 from '@/components/layout/layout1'
import Carousel from '@/components/carousel'
import Link from 'next/link'
import { BtnLg } from '@/components/common/buttons/'

// TODO: 問牙牙條RWD的時候滿版兩旁要留多少margin ex. 卡片輪播

export default function Home() {
  return (
    <>
      <Layout1>
        <Head>
          <title>GoHealthier</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <main>
          <section className="key-visual-pc">
            <div className="hero">
              <div className="container fixed-960 p-0">
                <div className="row g-0">
                  <div className="col-md-8 hero-text">
                    <h1 className="text-primary pe-1">
                      愛默生曾經說過健康是人生第一財富。
                    </h1>
                    <Link href="#">
                      <h3>{`[ Start ]`}</h3>
                    </Link>
                  </div>
                  <div className="hero-image">
                    <img src="/hero-img.png" />
                  </div>
                </div>
              </div>
            </div>

            <div className="cta-1 bg-secondary">
              <div className="container fixed-960 p-0">
                <div className="row g-0 justify-content-between">
                  <div className="col-md-4 cta-1-img">
                    <img src="/marisa-howenstine-nFsOlSE9Mn8-unsplash.jpg" />
                  </div>
                  <div className="col-md-7">
                    <h3>活力無限，擁抱健康</h3>
                    <p>
                      運動是保持健康的關鍵，活力啟點幫您找到最佳運動場所。立即搜尋，讓健康和活力成為生活常態！
                      <br />
                      讓我們活到老，動到老！
                    </p>
                    <BtnLg>找場館</BtnLg>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <div className="page-wrap">
            <section className="cta-2">
              <div className="container-fluid">
                <h3>你是不是有這些困擾呢？</h3>
                <div className="row cta-2-cards justify-content-center align-items-center m-0">
                  <div className="cta-knee col-md-4 d-flex flex-column justify-content-center align-items-center bg-secondary">
                    <h4 className="num-title">
                      {'['}01{']'}
                    </h4>
                    <h5>你會膝蓋痛嗎？</h5>
                    <img src="/knee.svg" className="d-block" />
                    <p>
                      膝蓋痛是否讓你很困擾？為何不試著透過運動來緩解呢？快加入我們吧！
                    </p>
                  </div>
                  <div className="cta-bored col-md-4 d-flex flex-column justify-content-center align-items-center">
                    <h4 className="num-title">
                      {'['}02{']'}
                    </h4>
                    <h5>生活很無聊嗎？</h5>
                    <img src="/bored.svg" className="d-block" />
                    <p>
                      運動是改善心情的最佳良方！從今天開始，每天花點時間運動，讓身心都煥然一新。
                    </p>
                  </div>
                  <div className="cta-sleepy col-md-4 d-flex flex-column justify-content-center align-items-center bg-secondary">
                    <h4 className="num-title">
                      {'['}03{']'}
                    </h4>
                    <h5>常常想睡嗎？</h5>
                    <img src="/sleepy.svg" className="d-block" />
                    <p>
                      想開始運動卻不知道能去哪裡嗎？點選下方按鈕，輸入您附近的地址來尋找場館吧！
                    </p>
                  </div>
                </div>
                <div className="row">
                  <div className="col d-flex justify-content-center">
                    <BtnLg>找解答</BtnLg>
                  </div>
                </div>
              </div>
            </section>

            <section className="popular lessons">
              <Carousel carouselTitle="熱門課程" />
              <div className="row">
                <div className="col d-flex justify-content-center">
                  <BtnLg>找課程</BtnLg>
                </div>
              </div>
            </section>

            <section className="popular coaches">
              <Carousel carouselTitle="熱門教練" />
              <div className="row">
                <div className="col d-flex justify-content-center">
                  <BtnLg>找教練</BtnLg>
                </div>
              </div>
            </section>

            <section className="popular articles">
              <Carousel carouselTitle="熱門文章" />
              <div className="row">
                <div className="col d-flex justify-content-center">
                  <BtnLg>找文章</BtnLg>
                </div>
              </div>
            </section>

            <section className="join-member">
              <div className="container-fluid p-0">
                <div className="row flex-column align-items-center text-center">
                  <div className="col-md-7 join-member-card bg-secondary">
                    <h3>加入會員 ?</h3>
                    <p>看完我們的網站心動了嗎？立馬點擊下面按鈕加入會員！</p>
                    <BtnLg>去健身</BtnLg>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </main>
      </Layout1>
    </>
  )
}
