import Head from 'next/head'
// import styles from '@/styles/home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>GoHealthier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>test layout</h1>
        <div>
          <h1>Scroll Down</h1>
          <p>Some content...</p>
        </div>
      </main>
    </>
  )
}
