// 功能類
import { useState, useEffect } from 'react'
import Head from 'next/head'

// 樣式 or 元件類
import Layout1 from '@/components/layout/layout1'
import Carousel from '@/components/carousel'
import Link from 'next/link'
import { BtnLg } from '@/components/common/buttons/'
import JoinMember from '@/components/joinMember'
import styles from '@/styles/home.module.css'

export default function Test() {
  return (
    <>
      <Layout1>
        <Head>
          <title>活力啟點</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <main className={`${styles.keyVisualPC}`}>
          <div className={`container-fluid p-0 hero`}>
            <div className={`row`}>
              <div className={`col-md-6`}>
                <h1>愛默生曾經說過健康是人生第一財富。</h1>
                <Link href="/#">
                  <h3 className={`${styles.startAction}`}>{`[ Start ]`}</h3>
                </Link>
              </div>
              <div className={`col-md-6`}>
                <img src="" />
              </div>
            </div>

            <div className={`row cta1`}>
              <div className="col-md-6">
                <img src="" />
              </div>
              <div className="col-md-6">
                <h3>活力無限，擁抱健康</h3>
                <p>
                  運動是保持健康的關鍵，活力啟點幫您找到最佳運動場所。立即搜尋，讓健康和活力成為生活常態！
                  讓我們活到老，動到老！
                </p>
                <div className="col">
                  <BtnLg>找場館</BtnLg>
                </div>
              </div>
            </div>
          </div>
        </main>
      </Layout1>
    </>
  )
}
