import React from 'react'
import Head from 'next/head'
import Layout1 from '@/components/layout/layout1'
import Carousel from '@/components/carousel'
import Link from 'next/link'

export default function Index() {
  return (
    <>
      <Layout1>
      <Head>
          <title>活力啟點教練</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <section>
            
        </section>
      </Layout1>
    </>
  )
}
